Ejercicios de Arrays y Matrices con NumPy

In [1]:
import numpy as np

Ejercicio 1: Crear un array de 10 elementos con ceros.

In [3]:
array_ceros = np.zeros(10)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ejercicio 2: Genera un array con los números del 1 al 20.

In [4]:
array_1_20 = np.arange(1,21)
print(array_1_20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Ejercicio 3: Crea un array con los números pares del 2 al 50.

In [5]:
pares = np.arange(2,51,2)
print(pares)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.

In [6]:
matriz = np.random.rand(4,4)
print(matriz)

[[0.67384763 0.32882794 0.99170252 0.58390724]
 [0.75981773 0.57338516 0.77862085 0.70139665]
 [0.27924689 0.17581986 0.13843404 0.94029019]
 [0.48563416 0.16034275 0.3535997  0.51837928]]


Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
suma = a + b
print(f"suma: {suma}")

suma: [5 7 9]


Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

In [9]:
m1 = np.random.randint(1, 11, (3, 3))
m2 = np.random.randint(1, 11, (3, 3))

# Multiplicación matricial (producto punto)
resultado_dot = np.dot(m1, m2) 
# O alternativamente: resultado_dot = m1 @ m2

print("Matriz 1:\n", m1)
print("Matriz 2:\n", m2)
print("Resultado:\n", resultado_dot)

Matriz 1:
 [[2 3 3]
 [3 6 5]
 [2 5 8]]
Matriz 2:
 [[10  1  3]
 [ 1  4  4]
 [ 9  3  9]]
Resultado:
 [[50 23 45]
 [81 42 78]
 [97 46 98]]


Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

In [10]:
datos = np.random.randint(1, 101, 15)

print(f"Array: {datos}")
print(f"Máximo: {datos.max()}")
print(f"Mínimo: {datos.min()}")
print(f"Promedio: {datos.mean()}")

Array: [82 81 94 51 46 27 40 89 39 98 80 63 88 32 85]
Máximo: 98
Mínimo: 27
Promedio: 66.33333333333333


Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

In [11]:
# Creamos del 1 al 25 y redimensionamos a 5x5
matriz_5x5 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_5x5)

print("Matriz:\n", matriz_5x5)
print("Diagonal:", diagonal)

Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna

In [12]:
matriz_rand_20 = np.random.randint(1, 21, (5, 5))

suma_columnas = matriz_rand_20.sum(axis=0)
suma_filas = matriz_rand_20.sum(axis=1)

print("Matriz:\n", matriz_rand_20)
print("Suma por columnas:", suma_columnas)
print("Suma por filas:", suma_filas)

Matriz:
 [[16 11  1  5  1]
 [ 9  9  9 20  8]
 [11 11  7 20 11]
 [ 7  1  7 18  1]
 [10  8  5 15 16]]
Suma por columnas: [53 40 29 78 37]
Suma por filas: [34 55 60 34 54]
