<a href="https://colab.research.google.com/github/BarbyJRigoni/Aprendizaje-Automatico/blob/main/Semana_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Ejercicios de Arrays y Matrices con NumPy

Ejercicio 1: Crear un array de 10 elementos con ceros.

In [ ]:
import numpy as np

In [ ]:
array_ceros = np.zeros(10)
print(array_ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Ejercicio 2: Genera un array con los números del 1 al 20.

In [ ]:
array_1_20 = np.arange(1,21)
print(array_1_20)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Ejercicio 3: Crea un array con los números pares del 2 al 50.

In [ ]:
pares = np.arange(2,51,2)
print(pares)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]


Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.

In [ ]:
matriz = np.random.rand(4,4)
print(matriz)

[[0.75305831 0.55536317 0.78668085 0.42356669]
 [0.2541878  0.48254962 0.00799412 0.02115221]
 [0.26199342 0.98543843 0.07392166 0.9690655 ]
 [0.29531509 0.48902497 0.26820567 0.44307063]]


Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
suma = a + b
print(f"suma: {suma}")

suma: [5 7 9]


Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

In [ ]:
m1 = np.random.randint(1, 11, (3, 3))
m2 = np.random.randint(1, 11, (3, 3))

# Multiplicación matricial (producto punto)
resultado_dot = np.dot(m1, m2)
# O alternativamente: resultado_dot = m1 @ m2

print("Matriz 1:\n", m1)
print("Matriz 2:\n", m2)
print("Resultado:\n", resultado_dot)

Matriz 1:
 [[ 1  3  8]
 [10  8  6]
 [ 2  6  6]]
Matriz 2:
 [[9 8 6]
 [2 7 3]
 [7 3 2]]
Resultado:
 [[ 71  53  31]
 [148 154  96]
 [ 72  76  42]]


Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

In [ ]:
datos = np.random.randint(1, 101, 15)

print(f"Array: {datos}")
print(f"Máximo: {datos.max()}")
print(f"Mínimo: {datos.min()}")
print(f"Promedio: {datos.mean()}")

Array: [74 77 94 64 11 10 15 53 87 57 20 20 62 77 62]
Máximo: 94
Mínimo: 10
Promedio: 52.2


Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

In [ ]:
# Creamos del 1 al 25 y redimensionamos a 5x5
matriz_5x5 = np.arange(1, 26).reshape(5, 5)
diagonal = np.diag(matriz_5x5)

print("Matriz:\n", matriz_5x5)
print("Diagonal:", diagonal)

Matriz:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Diagonal: [ 1  7 13 19 25]


Ejercicio 10 : Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna

In [ ]:
matriz_rand_20 = np.random.randint(1, 21, (5, 5))

suma_columnas = matriz_rand_20.sum(axis=0)
suma_filas = matriz_rand_20.sum(axis=1)

print("Matriz:\n", matriz_rand_20)
print("Suma por columnas:", suma_columnas)
print("Suma por filas:", suma_filas)

Matriz:
 [[ 2  5 20 17  9]
 [12  7  7 14  8]
 [ 5  1  2 12  2]
 [19 10 17 12  5]
 [ 9  6 16 13  3]]
Suma por columnas: [47 29 62 68 27]
Suma por filas: [53 48 22 63 47]
